---
abstract: 'Subroutine calls over the network using common serialization'
author:
  - 'Oliver Gorwits C<< <oliver.gorwits@oucs.ox.ac.uk> >>'
build_requires:
  IO::Socket::SSL: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  URI: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RPC-Serialized
no_index:
  directory:
    - inc
    - t
    - examples
recommends:
  IO::Socket::NegKrb5: 0
  IO::Socket::SSL: 0
  Net::Server::PreFork: 0
  URI: 0
requires:
  Class::Accessor::Fast::Contained: 0.05
  Data::Serializer: 0.41
  Exception::Class: 1.19
  Module::MultiConf: 0.02
  Readonly: 1.03
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.0701
